development:
  adapter: postgresql
  database: caitlin_tax_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  database: caitlin_tax_production
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  database: caitlin_tax_test
  pool: 5
  username:
  password:
